### ISSUE TITLE
3.1 level of the hentai peach

### ISSUE THREAD

**Issue by Veliusnightmare** [ivanaedler/MIMPUT#31]
![untitled](https://cloud.githubusercontent.com/assets/27245763/24888424/68ca4856-1e31-11e7-8cd1-7f3480694771.png)
heya this is veliusnightmare and this is what happened after i hold the bomb to blow up to destroy the wall, and it only explode the middle two blocks. For some reason, peach was unable to move even when i go to setting or the white screen with facts. she won't move. so i press del to make her lose a life and when i come back the wall become normal again. and when i try to throw the bomb they become normal and land in the bottom pit.

**Comment by ivanaedler** [comment]
Fixed in version 3.31
