### ISSUE TITLE
classic nymph gait not working

### ISSUE THREAD

**Issue by leoloc** [ivanaedler/MIMPUT#32]
peach continues with the slutty walk even with the classic nymph gait on

**Comment by ivanaedler** [comment]
Here, when I start the game, the princess walks 'normally' when Classic is OFF,
 and she walks 'classic mode' when Classic is ON (image below)

Remember that 'classic nymph gait' being NO doesnt mean a slutty Princess will walk in embarrassed mode. This switch is just to change classic nymph gait with new nymph gait.

 [http://oi65.tinypic.com/250p3sy.jpg](url)

**Comment by leoloc** [comment]
I understand, but this is a good option to add in the settings, I
prefer it walking normal and I think others should also think the same


2017-04-21 19:48 GMT-03:00 Ivan Aedler <notifications@github.com>:

**Comment by ivanaedler** [comment]
So, just for me to understand better.
When you say 'Peach continues with the slutty walk even with the classic nymph gait on', you mean you want an option to make her walk embarrassed all the time?

Lets remember that:
1) When she is naked and innocent, she walks embarrassed. 
2) When she is NOT naked and innocent, she can walk in 'normal or 'classic' mode (this works already)
3) When she is a nymph, she can be either clothed or naked. She will always walk in 'normal' or 'classic' mode (this works already).

So you want: Classic Nymph Gait: Embarrassed, Classic and Nymph walk styles?
So this will happen?
4) When she is a innocent or a nymph, she can be either clothed or naked. She will always walk in 'embarrassed mode'.

**Comment by leoloc** [comment]
Naked, when she stops moving, and the always innocent is off she puts a
hand on her waist and another on her head and begins to shake

2017-05-05 2:24 GMT-03:00 Ivan Aedler <notifications@github.com>:

**Comment by ivanaedler** [comment]
Oh, so if I understand this case, the fact she puts her hand on her waist and shake is when she is a nymph in the game, or 'always a nymph' OPTION is on. She will continue doing that if she is already a nymph and the option is 'LET HER CHOOSE'. 

I'll then make she not do the shaking if 'always innocent' is on.
