### ISSUE TITLE
Character Portait Issue

### ISSUE THREAD

**Issue by slpowerhouse** [ivanaedler/MIMPUT#33]
I have noticed for a while now that there is a glitch that has been occurring for a while now in the game.  When I am playing as any character besides normal peach, fire peach, peach PS, fire peach PS, and krystal the portrait changes to the next character in the list when the horny bar raises to the point that the portrait should change.

when playing as tanned peach the portrait changes from peach to daisy as peach gets more horny. when playing as daisy the portrait changes to rosalina and when playing as rosalina the portrait disappears altogether.

I am attaching a screen shot showing the glitch happening as rosalina.
![peachs untold tale 3 33 portrait glitch with debug menu](https://cloud.githubusercontent.com/assets/28659597/26015390/ce74a8ac-372e-11e7-876c-49d1cf73d93b.png)

**Comment by ivanaedler** [comment]
Fixed in 3.34
