### ISSUE TITLE
Quiero ayudarte a traducir todos los textos. --- I want to help you translate all the texts.

### ISSUE THREAD

**Issue by darks24** [ivanaedler/MIMPUT#38]
I want to help you translate all the texts but when I edit, I correct and save the changes. Changes are not generated WHY? 

Quiero ayudarte a traducir todos los textos pero cuando edito, corrijo y guardo los cambios. No se generan los cambios POR QUE?

**Comment by ivanaedler** [comment]
Hello there! Sorry about the delay, I was moving from cities!
You need to use GIT program to download to your machine, so you can change it, save it, then you make a PULL REQUEST. You should take the latest spanish version, then work on it.

You can also download it to your machine (without GIT) then upload it in LOK site (making a new post) in http://legendofkrystal.com/forum/viewtopic.php?f=34&t=2265
