### ISSUE TITLE
How do I upload the downloaded XML file to synchronize the original XML file.

### ISSUE THREAD

**Issue by darks24** [ivanaedler/MIMPUT#39]
English: How do I upload the downloaded XML file to synchronize the original XML file.

I am working on the translation of all the texts from English to Spanish but I have the file -XMLLanguage_sp.xml- On my pc but I want to upload it to synchronize it with the original. Could someone help me with this?

Spanish: Como subo el archivo XML descargado para sincronizar el archivo XML original.

Estoy trabajando en la traducción de todos los textos de inglés al español pero tengo el archivo -XMLLanguage_sp.xml- En mi pc pero quiero subirlo para sincronizarlo con el original. Alguien me podría ayudar en esto?

**Comment by ivanaedler** [comment]
Hello there! I am sorry for the delay, I was moving to another city!
I noticed your two PULL REQUESTs but I was away.
I'll do it on day 2 or 3 of january.

Thank you for your work!
