### ISSUE TITLE
The pipe World 7

### ISSUE THREAD

**Issue by NocPUT** [ivanaedler/MIMPUT#41]
peach's not entering the pipe neither to come back at this part: 
![image](https://user-images.githubusercontent.com/34816195/34328132-6b179760-e8bd-11e7-9d58-ab07ceb06096.png)

Ps: it's some especial place that has the toad's bonus level on it.

**Comment by ivanaedler** [comment]
Checking!

**Comment by ivanaedler** [comment]
Fixed in version 3.45
